---
openapi: 3.0.3
info:
  title: rspec-openapi
paths:
  "/tables":
    get:
      summary: tables#index
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      - name: per
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: returns a list of tables
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: 'null'
                    database:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
        '401':
          description: does not return tables if unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: tables#create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: 'null'
                database_id:
                  type: integer
                table:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: 'null'
                    database_id:
                      type: integer
      responses:
        '201':
          description: returns a table
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: 'null'
                  database:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
  "/tables/{id}":
    get:
      summary: tables#show
      parameters:
      - name: id
        in: path
        schema:
          type: integer
      responses:
        '200':
          description: returns a table
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: 'null'
                  database:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        '401':
          description: does not return a table if unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: does not return a table if not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    patch:
      summary: tables#update
      parameters:
      - name: id
        in: path
        schema:
          type: integer
      responses:
        '200':
          description: returns a table
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: 'null'
                  database:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
    delete:
      summary: tables#destroy
      parameters:
      - name: id
        in: path
        schema:
          type: integer
      responses:
        '200':
          description: returns a table
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: 'null'
                  database:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
