name: test
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby:2.5
          - ruby:2.6
          - ruby:2.7
          - ruby:3.0
        rails:
          - 6.0.5
          - 6.1.6
          - 7.0.3
        exclude:
          - ruby: ruby:2.5
            rails: 7.0.3
          - ruby: ruby:2.6
            rails: 7.0.3
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v2
      - name: bundle install
        run: bundle install -j$(nproc) --retry 3
      - run: bundle exec rspec
        timeout-minutes: 1
